eeazycrm/accounts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.widgets import TextArea
from wtforms.validators import DataRequired, Email
from wtforms_sqlalchemy.fields import QuerySelectField

from eeazycrm.users.models import User


class NewAccount(FlaskForm):
    name = StringField('Account Name', validators=[DataRequired(message='Account name is mandatory')])
    website = StringField('Website')
    email = StringField('Email',
                        validators=[DataRequired(message='Email address is mandatory'),
                                    Email(message='Please enter a valid email address e.g. abc@yourcompany.com')])
    phone = StringField('Phone')
    address_line = StringField('Address')
    addr_state = StringField('State')
    addr_city = StringField('City')
    post_code = StringField('Postcode')
    country = StringField('Country')
    notes = StringField('Notes', widget=TextArea())
    assignees = QuerySelectField('Assign To', query_factory=User.user_list_query, get_pk=lambda a: a.id,
                                 get_label=User.get_label, default=User.get_current_user)
    submit = SubmitField('Create New Account')


def filter_accounts_adv_filters_query():
    return [
        {'id': 1, 'title': 'Active'},
        {'id': 2, 'title': 'Inactive'},
        {'id': 3, 'title': 'Created Today'},
        {'id': 4, 'title': 'Created Yesterday'},
        {'id': 5, 'title': 'Created In Last 7 Days'},
        {'id': 6, 'title': 'Created In Last 30 Days'}
    ]


class FilterAccounts(FlaskForm):
    txt_search = StringField()
    assignees = QuerySelectField(query_factory=User.user_list_query, get_pk=lambda a: a.id,
                                 get_label=User.get_label, allow_blank=True, blank_text='[-- Select Owner --]')
    advanced_user = QuerySelectField(query_factory=filter_accounts_adv_filters_query,
                                     get_pk=lambda a: a['id'],
                                     get_label=lambda a: a['title'],
                                     allow_blank=True, blank_text='[-- advanced filter --]')

    submit = SubmitField('Filter Accounts')

eeazycrm/contacts/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed
from wtforms import StringField, SubmitField
from wtforms.widgets import TextArea
from wtforms.validators import DataRequired, Email
from wtforms_sqlalchemy.fields import QuerySelectField

from eeazycrm.users.models import User
from eeazycrm.accounts.models import Account


class NewContact(FlaskForm):
    first_name = StringField('First Name')
    last_name = StringField('First Name', validators=[DataRequired(message='Last name is mandatory')])
    email = StringField('Email',
                        validators=[DataRequired(message='Email address is mandatory'),
                                    Email(message='Please enter a valid email address e.g. abc@yourcompany.com')])
    phone = StringField('Phone')
    mobile = StringField('Mobile')
    avatar = FileField('Contact Avatar', validators=[FileAllowed(['jpg', 'jpeg', 'png'])])
    address_line = StringField('Address')
    addr_state = StringField('State')
    addr_city = StringField('City')
    post_code = StringField('Postcode')
    country = StringField('Country')
    notes = StringField('Notes', widget=TextArea())
    accounts = QuerySelectField('Account', query_factory=Account.account_list_query, get_pk=lambda a: a.id,
                                 get_label=Account.get_label, blank_text='Select An Account', allow_blank=True,
                                validators=[DataRequired(message='Please choose an account for the contact')])
    assignees = QuerySelectField('Assign To', query_factory=User.user_list_query, get_pk=lambda a: a.id,
                                 get_label=User.get_label, default=User.get_current_user)
    submit = SubmitField('Create New Contact')


def filter_contacts_adv_filters_query():
    return [
        {'id': 1, 'title': 'Created Today'},
        {'id': 2, 'title': 'Created Yesterday'},
        {'id': 3, 'title': 'Created In Last 7 Days'},
        {'id': 4, 'title': 'Created In Last 30 Days'}
    ]


class FilterContacts(FlaskForm):
    txt_search = StringField()
    accounts = QuerySelectField(query_factory=Account.account_list_query, get_pk=lambda a: a.id,
                                get_label=Account.get_label, blank_text='[-- Select Account--]', allow_blank=True)
    assignees = QuerySelectField(query_factory=User.user_list_query, get_pk=lambda a: a.id,
                                 get_label=User.get_label, allow_blank=True, blank_text='[-- Select Owner --]')
    advanced_user = QuerySelectField(query_factory=filter_contacts_adv_filters_query,
                                     get_pk=lambda a: a['id'],
                                     get_label=lambda a: a['title'],
                                     allow_blank=True, blank_text='[-- advanced filter --]')

    submit = SubmitField('Filter Contacts')

eeazycrm/install/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, BooleanField
from wtforms.validators import DataRequired, Length, Email, EqualTo
from wtforms_sqlalchemy.fields import QuerySelectField

from eeazycrm.settings.models import Currency, TimeZone


class NewSystemUser(FlaskForm):
    first_name = StringField('First Name', validators=[DataRequired(message='Please enter your first name')])
    last_name = StringField('Last Name',
                            validators=[DataRequired(message='Please enter your last name'), Length(min=2, max=20)])
    email = StringField('Email',
                        validators=[DataRequired(
                            message='Email address is mandatory'),
                            Email(message='Please enter a valid email address e.g. abc@yourcompany.com')])
    password = PasswordField('Password',
                             validators=[DataRequired(message='Password is mandatory')])
    confirm_password = PasswordField('Confirm Password',
                                     validators=[DataRequired(
                                         message='Confirm Password is mandatory'),
                                         EqualTo('password', 'Passwords do not match')])
    submit = SubmitField('Next: Setup Company Details')


class CurrencyTz(FlaskForm):
    currency = QuerySelectField('Default Currency', query_factory=Currency.get_list_query, get_pk=lambda a: a.id,
                                get_label='name',
                                validators=[DataRequired(message='Please select default currency')])
    time_zone = QuerySelectField('Your Time Zone', query_factory=TimeZone.get_list_query, get_pk=lambda a: a.id,
                                 get_label='name',
                                 validators=[DataRequired(message='Please select your timezone')])
    submit = SubmitField('Next: Finish Installation')


class FinishInstall(FlaskForm):
    import_sample_data = BooleanField('Install Sample Data')
    submit = SubmitField('Complete Installation')

eeazycrm/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_bcrypt import Bcrypt
from flask_login import LoginManager

import os

from .config import DevelopmentConfig, TestConfig, ProductionConfig

# database handle
db = SQLAlchemy(session_options={"autoflush": False})

# encryptor handle
bcrypt = Bcrypt()

# manage user login
login_manager = LoginManager()

# function name of the login route that
# tells the path which facilitates authentication
login_manager.login_view = 'users.login'


def run_install(app_ctx):
    from eeazycrm.install.routes import install
    app_ctx.register_blueprint(install)
    return app_ctx


def create_app(config_class=ProductionConfig):
    app = Flask(__name__, instance_relative_config=True)

    if os.getenv('FLASK_ENV') == 'development':
        config_class = DevelopmentConfig()
    elif os.getenv('FLASK_ENV') == 'production':
        config_class = ProductionConfig()
    elif os.getenv('FLASK_ENV') == 'testing':
        config_class = TestConfig()

    app.config.from_object(config_class)
    app.url_map.strict_slashes = False
    app.jinja_env.globals.update(zip=zip)

    db.init_app(app)
    bcrypt.init_app(app)
    login_manager.init_app(app)

    with app.app_context():
        # check if the config table exists, otherwise run install
        engine = db.get_engine(app)
        if not engine.dialect.has_table(engine, 'app_config'):
            return run_install(app)
        else:
            from eeazycrm.settings.models import AppConfig
            row = AppConfig.query.first()
            if not row:
                return run_install(app)

        # application is installed so extends the config
        from eeazycrm.settings.models import AppConfig, Currency, TimeZone
        app_cfg = AppConfig.query.first()
        app.config['def_currency'] = Currency.get_currency_by_id(app_cfg.default_currency)
        app.config['def_tz'] = TimeZone.get_tz_by_id(app_cfg.default_timezone)

        # include the routes
        # from eeazycrm import routes
        from eeazycrm.main.routes import main
        from eeazycrm.users.routes import users
        from eeazycrm.leads.routes import leads
        from eeazycrm.accounts.routes import accounts
        from eeazycrm.contacts.routes import contacts
        from eeazycrm.deals.routes import deals
        from eeazycrm.settings.routes import settings
        from eeazycrm.settings.app_routes import app_config
        from eeazycrm.reports.routes import reports

        # register routes with blueprint
        app.register_blueprint(main)
        app.register_blueprint(users)
        app.register_blueprint(settings)
        app.register_blueprint(app_config)
        app.register_blueprint(leads)
        app.register_blueprint(accounts)
        app.register_blueprint(contacts)
        app.register_blueprint(deals)
        app.register_blueprint(reports)
        return app

eeazycrm/accounts/routes.py
from flask import Blueprint, session
from flask_login import current_user, login_required
from flask import render_template, flash, url_for, redirect, request
from sqlalchemy import or_, text
from datetime import date, timedelta

from eeazycrm import db
from .models import Account
from eeazycrm.common.paginate import Paginate
from eeazycrm.common.filters import CommonFilters
from .forms import NewAccount, FilterAccounts, filter_accounts_adv_filters_query

from eeazycrm.rbac import check_access
from wtforms import Label

accounts = Blueprint('accounts', __name__)


def set_filters(f_id, module):
    today = date.today()
    filter_d = True
    if f_id == 1:
        filter_d = text("Account.is_active=True")
    elif f_id == 2:
        filter_d = text("Account.is_active=False")
    elif f_id == 3:
        filter_d = text("Date(%s.date_created)='%s'" % (module, today))
    elif f_id == 4:
        filter_d = text("Date(%s.date_created)='%s'" % (module, (today - timedelta(1))))
    elif f_id == 5:
        filter_d = text("Date(%s.date_created) > current_date - interval '7' day" % module)
    elif f_id == 6:
        filter_d = text("Date(%s.date_created) > current_date - interval '30' day" % module)
    return filter_d


def set_date_filters(filters, module, key):
    filter_d = True
    if request.method == 'POST':
        if filters.advanced_user.data:
            filter_d = set_filters(filters.advanced_user.data['id'], module)
            session[key] = filters.advanced_user.data['id']
    else:
        if key in session:
            filter_d = set_filters(session[key], module)
            filters.advanced_user.data = filter_accounts_adv_filters_query()[session[key] - 1]
    return filter_d


def reset_accounts_filters():
    if 'accounts_owner' in session:
        session.pop('accounts_owner', None)
    if 'accounts_search' in session:
        session.pop('accounts_search', None)
    if 'account_active' in session:
        session.pop('account_active', None)
    if 'accounts_date_created' in session:
        session.pop('accounts_date_created', None)


@accounts.route("/accounts", methods=['GET', 'POST'])
@login_required
@check_access('accounts', 'view')
def get_accounts_view():
    filters = FilterAccounts()
    search = CommonFilters.set_search(filters, 'accounts_search')
    owner = CommonFilters.set_owner(filters, 'Account', 'accounts_owner')
    advanced_filters = set_date_filters(filters, 'Account', 'accounts_date_created')

    query = Account.query.filter(or_(
        Account.name.ilike(f'%{search}%'),
        Account.website.ilike(f'%{search}%'),
        Account.email.ilike(f'%{search}%'),
        Account.phone.ilike(f'%{search}%'),
        Account.address_line.ilike(f'%{search}%'),
        Account.addr_state.ilike(f'%{search}%'),
        Account.addr_city.ilike(f'%{search}%'),
        Account.post_code.ilike(f'%{search}%')
    ) if search else True) \
        .filter(owner) \
        .filter(advanced_filters) \
        .order_by(Account.date_created.desc())

    return render_template("accounts/accounts_list.html", title="Accounts View",
                           accounts=Paginate(query=query), filters=filters)


@accounts.route("/accounts/edit/<int:account_id>", methods=['GET', 'POST'])
@login_required
@check_access('accounts', 'update')
def update_account(account_id):
    account = Account.get_account(account_id)
    if not account:
        return redirect(url_for('accounts.get_accounts_view'))

    form = NewAccount()
    if request.method == 'POST':
        if form.validate_on_submit():
            account.name = form.name.data
            account.website = form.website.data
            account.email = form.email.data
            account.phone = form.phone.data
            account.address_line = form.address_line.data
            account.addr_state = form.addr_state.data
            account.addr_city = form.addr_city.data
            account.post_code = form.post_code.data
            account.country = form.country.data
            account.account_owner = form.assignees.data
            account.notes = form.notes.data
            db.session.commit()
            flash('The account has been successfully updated', 'success')
            return redirect(url_for('accounts.get_account_view', account_id=account.id))
        else:
            print(form.errors)
            flash('Accounts update failed! Form has errors', 'danger')
    elif request.method == 'GET':
        form.name.data = account.name
        form.website.data = account.website
        form.email.data = account.email
        form.phone.data = account.phone
        form.address_line.data = account.address_line
        form.addr_state.data = account.addr_state
        form.addr_city.data = account.addr_city
        form.post_code.data = account.post_code
        form.country.data = account.country
        form.assignees.data = account.account_owner
        form.notes.data = account.notes
        form.submit.label = Label('update_account', 'Update Account')
    return render_template("accounts/new_account.html", title="Update Account", form=form)


@accounts.route("/accounts/<int:account_id>")
@login_required
@check_access('accounts', 'view')
def get_account_view(account_id):
    account = Account.query.filter_by(id=account_id).first()
    return render_template("accounts/account_view.html", title="View Account", account=account)


@accounts.route("/accounts/new", methods=['GET', 'POST'])
@login_required
@check_access('accounts', 'create')
def new_account():
    form = NewAccount()
    if request.method == 'POST':
        if form.validate_on_submit():
            account = Account(name=form.name.data,
                              website=form.website.data,
                              email=form.email.data,
                              phone=form.phone.data,
                              address_line=form.address_line.data,
                              addr_state=form.addr_state.data,
                              addr_city=form.addr_city.data,
                              post_code=form.post_code.data,
                              country=form.country.data,
                              notes=form.notes.data)

            if current_user.is_admin:
                account.account_owner = form.assignees.data
            else:
                account.account_owner = current_user

            db.session.add(account)
            db.session.commit()
            flash('Account has been successfully created!', 'success')
            return redirect(url_for('accounts.get_accounts_view'))
        else:
            for error in form.errors:
                print(error)
            flash('Your form has errors! Please check the fields', 'danger')
    return render_template("accounts/new_account.html", title="New Account", form=form)


@accounts.route("/accounts/del/<int:account_id>")
@login_required
@check_access('accounts', 'delete')
def delete_account(account_id):
    Account.query.filter_by(id=account_id).delete()
    db.session.commit()
    flash('Account removed successfully!', 'success')
    return redirect(url_for('accounts.get_accounts_view'))


@accounts.route("/accounts/reset_filters")
@login_required
@check_access('accounts', 'view')
def reset_filters():
    reset_accounts_filters()
    return redirect(url_for('accounts.get_accounts_view'))

eeazycrm/templates/accounts/account_view.html
{% extends "layout.html" %}
    {% block content %}
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h2 class="h4">{% if title %}{{title}}{% else %}No Title{% endif %}</h2>
        <div class="btn-toolbar mb-2 mb-md-0">
            <a href="{{ url_for('accounts.update_account', account_id=account.id) }}"
               class="btn btn-md btn-outline-primary mr-2" role="button">
                <span data-feather="edit-2"></span>
                  Edit
            </a>
            <a href="#" class="btn btn-md btn-outline-secondary mr-2" data-toggle="modal" data-target="#viewContactsModal" role="button">
                <span data-feather="users"></span>
                  View Contacts
            </a>
            <a href="{{ url_for('accounts.get_accounts_view') }}" class="btn btn-md btn-outline-secondary" role="button">
                <span data-feather="arrow-left"></span>
                  Back to List
            </a>
        </div>
    </div>

    <!-- Modal -->
                <div class="modal fade" id="viewContactsModal" tabindex="-1" role="dialog" aria-labelledby="viewContactsModalLabel" aria-hidden="true">
                  <div class="modal-dialog modal-lg" role="document">
                    <div class="modal-content">
                      <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Contacts</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                          <span aria-hidden="true">&times;</span>
                        </button>
                      </div>
                      <div class="modal-body text-center">
                        {% if account.contacts|length > 0 %}
                          <div class="mt-2 mb-4">Contacts of <strong>{{ account.name }}</strong></div>
                          <table class="table table-striped table-hover">
                            <thead class="thead-light">
                                <tr>
                                    <th>Contact Name</th>
                                    <th>Contact Email</th>
                                </tr>
                            </thead>
                              <tbody>
                                {% for contact in account.contacts %}
                                    <tr>
                                        <td>{{ contact.first_name }} {{ contact.last_name }}</td>
                                        <td>{{ contact.email }}</td>
                                    </tr>
                                {% endfor %}
                              </tbody>
                          </table>
                          {% else %}
                          <div class="mt-4 mb-4">No contacts have been created for <strong>{{ account.name }}</strong></div>
                          <a href="#" class="btn btn-md btn-outline-primary mb-4" role="button">
                              <span data-feather="users"></span> Create New Contact
                          </a>
                          {% endif %}
                      </div>
                      <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                      </div>
                    </div>
                  </div>
                </div>

    <div class="row">
        <div class="col-5">
            <ul class="list-group list-group-flush">
                <li class="list-group-item g_field">
                  <div class="label">Account Name</div>
                  <div class="text">{{ account.name if account.name else '_' }}</div>
              </li>
                <li class="list-group-item g_field">
                  <div class="label">Email</div>
                    {% if account.email %}
                        <div class="text">
                            <span data-feather="mail" class="mr-1"></span>
                            <a href="mailto: {{ account.email }}">{{ account.email }}</a>
                        </div>
                    {% else %}
                        <div class="text"><span data-feather="mail"></span> _</div>
                    {% endif %}
              </li>
              <li class="list-group-item g_field">
                  <div class="label">Website</div>
                  {% if account.website %}
                  <div class="text">
                      <span data-feather="globe" class="mr-1"></span>
                      <a href="{{ account.website }}" target="_blank">{{ account.website }}</a>
                  </div>
                  {% else %}
                    <div class="text"><span data-feather="globe"></span> _</div>
                  {% endif %}
              </li>

                <li class="list-group-item g_field">
                  <div class="label">Phone</div>
                  <div class="text"><span data-feather="phone" class="mr-1"></span> {{ account.phone if account.phone else '_' }}</div>
              </li>

                <li class="list-group-item g_field">
                  <div class="label">Owner</div>
                    {% if account.account_owner %}
                    <div class="text">
                        <div class="mt-1">
                            {% with owner=account.account_owner %}{% include 'common/owner_cell.html' %}{% endwith %}
                        </div>
                    </div>
                    {% else %}
                        <div class="text">_</div>
                    {% endif %}
              </li>

            </ul>
        </div>
        <div class="col-5">
            <ul class="list-group list-group-flush">
                <li class="list-group-item g_field col-12">
                  <div class="label">Address</div>
                  <div class="text">{{ account.address_line if account.address_line else '_' }}</div>
              </li>
              <li class="list-group-item g_field col-12">
                  <div class="row">
                      <div class="col-6">
                          <div class="label">State</div>
                          <div class="text">{{ account.addr_state if account.addr_state else '_' }}</div>
                      </div>
                      <div class="col-6">
                          <div class="label">City</div>
                          <div class="text">{{ account.addr_city if account.addr_city else '_' }}</div>
                      </div>
                  </div>
              </li>
                <li class="list-group-item g_field col-12">
                    <div class="row">
                        <div class="col-6">
                            <div class="label">Postcode</div>
                            <div class="text">{{ account.post_code if account.post_code else '_' }}</div>
                        </div>
                        <div class="col-6">
                            <div class="label">Country</div>
                            <div class="text">{{ account.country if account.country else '_' }}</div>
                        </div>
                    </div>
              </li>
            </ul>
        </div>
    </div>
    <div class="row">
        <div class="col-10">
            <div></div>
            <ul class="list-group list-group-flush">
                <li class="list-group-item g_field col-12">
                    <div class="label">Notes</div>
                    <div class="text">{{ account.notes if account.notes else '_' }}</div>
                </li>
            </ul>
        </div>
    </div>
    {% endblock %}

eeazycrm/templates/accounts/accounts_list.html
{% extends "layout.html" %}
    {% block content %}
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h2 class="h4">{% if title %}{{title}}{% else %}No Title{% endif %}</h2>
        <div class="btn-toolbar mb-2 mb-md-0">
            {% if current_user.is_admin %}
            <a class="btn btn-sm btn-outline-secondary mr-2" role="button" href="{{ url_for('leads.import_bulk_leads') }}">
                <span data-feather="upload"></span>
                  import accounts ...
            </a>
            {% endif %}
            <a class="btn btn btn-sm btn-outline-primary" role="button" href="{{ url_for('accounts.new_account') }}">
                <span data-feather="plus"></span>
                  New
            </a>
        </div>
    </div>
    {% include "accounts/filters.html" %}
    {% if accounts.items()|length > 0 %}
        <div class="table-responsive">
            <table class="table table-striped table-hover fixed-layout-table">
              <thead class="thead-light">
                <tr>
                  <th width="40" scope="col">
                      <input type="checkbox" id="select_all" value="all" />
                  </th>
                    <th width="150"></th>
                    <th width="300" scope="col">Account Name</th>
                  <th width="250" scope="col">Email</th>
                  <th width="150" scope="col">Website</th>
                  <th width="150" scope="col">Phone</th>
                    <th width="250" scope="col">Address</th>
                    <th width="250" scope="col">State</th>
                    <th width="200" scope="col">City</th>
                    <th width="100" scope="col">Pincode</th>
                    <th width="100" scope="col">Country</th>
                    <th width="100" scope="col">Is Active</th>
                    <th width="200" scope="col">Owner</th>
                    <th width="200" scope="col">Date Created</th>
                </tr>
              </thead>
              <tbody>
                {% for account in accounts.items() %}
                <tr>
                  <th scope="row">
                      <input class="cb" type="checkbox" value="{{ account.id }}" />
                  </th>
                    <th>
                        <a href="{{ url_for('accounts.update_account', account_id=account.id) }}" class="btn btn-outline-secondary btn-sm mr-1" role="button">
                            <span data-feather="edit"></span>
                        </a>
                        <a href="#" class="btn btn-outline-secondary btn-sm mr-1"
                           data-target="#accountDeleteNotificationModal_{{ account.id }}" data-toggle="modal" role="button">
                            <span data-feather="trash"></span>
                        </a>
                        {% with acc=account %}
                            {% include 'accounts/single_account_delete_modal.html' %}
                        {% endwith %}
                        <a href="{{ url_for('accounts.get_account_view', account_id=account.id) }}"
                           class="btn btn-outline-secondary btn-sm mr-1" role="button">
                            <span data-feather="arrow-up-right"></span>
                        </a>
                    </th>
                    <td>{{ account.name }}</td>
                  <td>{{ account.email }}</td>
                  <td>
                      {% if account.website %}
                        <a href="{{ account.website }}" target="_blank">{{ account.website }}</a>
                      {% endif %}
                  </td>
                    <td>{{ account.phone }}</td>
                    <td>{{ account.address_line }}</td>
                    <td>{{ account.addr_state }}</td>
                    <td>{{ account.addr_city }}</td>
                    <td>{{ account.post_code }}</td>
                    <td>{{ account.country }}</td>
                    <td>{{ account.is_active }}</td>
                    <td>{% with owner=account.account_owner %}{% include 'common/owner_cell.html' %}{% endwith %}</td>
                    <td>{{ account.date_created.strftime('%Y-%m-%d') if account.date_created }}</td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
        </div>

        <!-- pagination -->
        {% if accounts.total_records > 10 %}
            {% with view_id="accounts.get_accounts_view", items=accounts %}
                {% include "common/pagination.html" %}
            {% endwith %}
        {% endif %}
    {% else %}
        <div class="container text-center pt-4">
            <div><span data-feather="eye-off"></span></div>
            <p>No accounts found. Please create your first account.</p>
        </div>
    {%  endif %}
<script>
    $(document).ready(function() {
        $('#select_all').on('click', function() {
            if ($(this).is(':checked')) {
                $('.cb').prop('checked', true);
            } else {
                $('.cb').prop('checked', false);
            }
        });
    });
</script>
{% endblock %}

eeazycrm/templates/accounts/filters.html
<form class="form-lead-filter" method="POST">
    {{ filters.hidden_tag() }} <!-- security 'csrf' token -->
    <div class="d-flex flex-column justify-content-between flex-wrap flex-md-nowrap pb-4 mb-3">
        <div class="mb-2"><strong>Filters</strong></div>
        <div class="btn-toolbar mb-2 mb-md-0">
            <div class="col-md-3 pl-0">
                {{ filters.txt_search(class="form-control from-control-lg", placeholder="search accounts ...") }}
            </div>
            {% if current_user.is_admin %}
            <div class="col-md-3 pl-0">
                <div class="form-group text-left">
                    {{ filters.assignees(class="my-select form-control") }}
                </div>
            </div>
            {% endif %}
            <div class="col-md-3 pl-0">
                <div class="form-group text-left">
                     {{ filters.advanced_user(class="my-select form-control") }}
                </div>
            </div>
        </div>
        <div class="btn-toolbar mb-1 mb-md-0">
            <div class="col-md-3 pl-0">
                {{ filters.submit(class="btn btn-md btn-outline-info mr-2") }}
                <a href="{{ url_for('accounts.reset_filters') }}" class="btn btn-md btn-outline-secondary" role="button">
                    <span data-feather="x-circle"></span>
                </a>
            </div>
        </div>
    </div>
</form>